### ISSUE TITLE
User roles

### ISSUE THREAD

**Issue by SkaeX** [BrainMaestro/FCE#100]
How do we intend to go about user roles? @BrainMaestro @tenorz007

**Comment by SkaeX** [comment]
We can use [this package](https://github.com/Zizaco/entrust). @BrainMaestro, @tenorz007

**Comment by BrainMaestro** [comment]
Yeah I think that one is good

**Comment by SkaeX** [comment]
I was looking around and found [this](https://github.com/JosephSilber/bouncer). It also looks interesting. @BrainMaestro @tenorz007 ?

**Comment by BrainMaestro** [comment]
Looks lighter
