### ISSUE TITLE
Multiple request files is unnecessary

### ISSUE THREAD

**Issue by tenorz007** [BrainMaestro/FCE#102]
Each resource should make use of only one request class instead of having so many different classes... @SkaeX @BrainMaestro

**Comment by SkaeX** [comment]
Okay Senior! We'll look at it.

**Comment by BrainMaestro** [comment]
That would involve checking what route the request is from and returning a different set of rules based on that. I'm not sure if that's better or worse. Thoughts?


Sent from Outlook Mobile






On Wed, Mar 16, 2016 at 5:07 AM -0700, "SkaeX" <notifications@github.com> wrote:





Okay Senior! We'll look at it.

---

**Comment by BrainMaestro** [comment]
We'll come back to this eventually since it won't change any functionality
