### ISSUE TITLE
License

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#124]
We need to decide on which license to use. Might be easier to identify what criteria we want in a license.

**Comment by SkaeX** [comment]
Check [this](http://choosealicense.com/) out.

**Comment by BrainMaestro** [comment]
Cool. Do we want to allow commercial use?

**Comment by BrainMaestro** [comment]
Look at [this](http://creativecommons.org/licenses/by-nc-nd/3.0/).

**Comment by SkaeX** [comment]
I like the CC license.

**Comment by BrainMaestro** [comment]
Cool. @tenorz007 thoughts?

**Comment by SkaeX** [comment]
Okay, it's CC then.

**Comment by BrainMaestro** [comment]
Can you add the license file
