### ISSUE TITLE
Optimize relationship between Evaluations and Question, QuestionSet

### ISSUE THREAD

**Issue by tenorz007** [BrainMaestro/FCE#13]
We need to find a way to use the pivot table on the evaluations and also make the pivot table accessible using eloquent.

**Comment by SkaeX** [comment]
How is this going?

**Comment by tenorz007** [comment]
You can work on it if you want, I am working on the reposiyories.

**Comment by BrainMaestro** [comment]
What exactly are you working on? I was planning on cleaning up the repositories

**Comment by SkaeX** [comment]
I was planning on understanding the relationships.

**Comment by tenorz007** [comment]
Go check the branch I published and the comments I put up on them.

**Comment by BrainMaestro** [comment]
@SkaeX Comment model? Why do you think so

**Comment by BrainMaestro** [comment]
I'll close this for now. If it becomes relevant later, we can reopen it
