### ISSUE TITLE
Front end

### ISSUE THREAD

**Issue by SkaeX** [BrainMaestro/FCE#134]
Let's agree on what CSS framework and JS library to use for the front end as mentioned in #133. @BrainMaestro @tenorz007.

- CSS Framework (e.g Material, Bulma, Muicss, whatever as long as it's not bootstrap)
- Javascript front-end library (e.g VueJs, React, Angular -- not really, others)

**Comment by BrainMaestro** [comment]
I vote VueJs and Bulma. Bulma's css classes are a lot cleaner and more semantic

**Comment by SkaeX** [comment]
I vote Vue.js. I prefer Muicss, but bulma is okay too.

**Comment by tenorz007** [comment]
I haven't really used most of them and I doubt I'll have the opportunity to
check them out any time soon.

**Comment by BrainMaestro** [comment]
A brief look should be enough


 to decide.

**Comment by SkaeX** [comment]
This issue has exceeded its lifetime. `Bulma` and `Vue.js` it is.

**Comment by SkaeX** [comment]
@tenorz007 Why?

**Comment by tenorz007** [comment]
Cause I haven't put in my views @SkaeX Compared to React, I would go with vue also since I haven't used it before. For the css, I know Material looks a bit bulky, but it looks like the most elegant one to me.

**Comment by SkaeX** [comment]
Sorry I'm a bit confused. Material as in [this](http://www.material-ui.com)?

**Comment by BrainMaestro** [comment]
That's a react implementation of Google's Material Design.
If we were going to use material, it'll have to be [this](http://getmdl.io). Which has that BEM thing that I don't like.

**Comment by tenorz007** [comment]
Why would it have to be that one

**Comment by BrainMaestro** [comment]
That's the official one from Google.

**Comment by BrainMaestro** [comment]
Well I guess it's Vuejs (3 votes) and Bulma (2 votes) then

**Comment by tenorz007** [comment]
He said he prefers Muicss,  and that he guesses Bulma is okay. Doesn't mean
he chooses it.

**Comment by BrainMaestro** [comment]
@SkaeX you're the decider now

**Comment by SkaeX** [comment]
I'm not really the decider (maybe compromiser). `Material` would be more ideal for the mobile devices they use for the evaluations. However, `Material` looked more complicated than `Bulma`. So of the two, I'll choose `Bulma`
