### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#157]
We need to implement navigation for the pages on the UI.
@SkaeX wants side nav like in #156. While I want top nav. not dissimilar to the way GitHub is.

[Side Nav](http://bulma.io/documentation/components/menu/), [Top Tab Bar](http://bulma.io/documentation/components/tabs/).

@tenorz007 Thoughts?

**Comment by SkaeX** [comment]
This is taking too long @BrainMaestro @tenorz007. 😟

**Comment by tenorz007** [comment]
I am trying to see what convention says, i'll look at your branch when I get back then I'll decided.

**Comment by tenorz007** [comment]
Side nav bar. Also, I believe the UI needs work..........

**Comment by SkaeX** [comment]
Thank you @tenorz007. Please endeavor to open an issue with the UI work needed. Cheers.
