### ISSUE TITLE
Disabling user access to the system

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#44]
Currently, we use soft deletes to disable user access to the system. The issue with this is that all historic data involving that user would be affected as well. 

Solutions

1. use `withTrashed` everywhere we retrieve users
1. use an `active` flag instead of soft deleting.

@tenorz007 and @SkaeX thoughts?

**Comment by tenorz007** [comment]
I think we should use both, when we delete we should set the active flag, so at least when you view the user, you would know he is not active.

**Comment by SkaeX** [comment]
I think we should go with active flags.

**Comment by BrainMaestro** [comment]
@tenorz007 if you use the flag, why would you also use soft deletes
