### ISSUE TITLE
Repository naming

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#45]
Currently we use an `SQL` prefix to name the repositories in #30. While this is good, I think `Eloquent` would be more appropriate and correct since the repositories are implemented through `Eloquent`.

@tenorz007 @SkaeX what do you think?

**Comment by tenorz007** [comment]
You have issues ohh, it was you that agreed this and you didn't think it
through. Why do you want to change it now?

**Comment by SkaeX** [comment]
LOL. Why did you go with `SQL` in the first place?

**Comment by BrainMaestro** [comment]
@SkaeX Because those repositories were meant to handle interfacing with `sql` databases like MySQL, SQLite, etc. We could add a new database in the future like MongoDB, then the repositories for that would have a `Mongo` prefix. That was the thought process behind it.

But since we use eloquent which doesn't cover every `sql` database, it makes more sense to rename it.

@tenorz007, No one gets everything perfectly on the first try. I thought it through and just explained my thought process. Change is allowed

**Comment by SkaeX** [comment]
Okay then.

**Comment by BrainMaestro** [comment]
You vote for renaming it?

**Comment by SkaeX** [comment]
Sure.

**Comment by BrainMaestro** [comment]
@tenorz007 you haven't said anything
