### ISSUE TITLE
Unit tests failing

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#48]
`Mysql` seems to be hiding some failures somehow. If you switch the database connection to `sqlite` and run the tests, some of them fail.

**Comment by SkaeX** [comment]
Found somethings:

- The question_question_set table has pivot table that was probably ignored whilst adding questions to a question set. The fields `position` and timestamps are not nullable, so `Integrity constraint violation`

**Comment by BrainMaestro** [comment]
Yeah I noticed the User one. They should both be easy fixes I think.

**Comment by SkaeX** [comment]
So do you have any proposal?

**Comment by BrainMaestro** [comment]
- Yeah the pivot table issue is because we didn't specify the columns in the relationship. And we aren't inserting any value there.
- You already diagnosed the `User` issue correctly.

**Comment by SkaeX** [comment]
Can I assign this to you then?

**Comment by BrainMaestro** [comment]
Sure
