### ISSUE TITLE
Repository create functions

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#55]
If you look at all our create functions, they accept arrays as arguments. This makes it unclear as to what exactly those functions need to create a new database record without looking up the columns.

I think we should change definitions like <br>`createSemester(array $attributes)` to `createSemester($season, $year)`. 
This makes it clearer and easier to use the function.

The selected answer in this [question](http://stackoverflow.com/questions/9092121/why-not-use-arrays-instead-of-many-parameters) explains it better. [This too](http://programmers.stackexchange.com/questions/212995/multiple-arguments-in-function-call-vs-single-array).

Thoughts? @tenorz007 @SkaeX

**Comment by tenorz007** [comment]
We are performing the same action on all of them....

**Comment by BrainMaestro** [comment]
Yes but it makes more sense to do 
`createSemester('Fall', 2015)` than `createSemester(['season' => 'Fall', 'year' => 2015])`

The actual array building should happen behind the scenes
