### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by SkaeX** [BrainMaestro/FCE#63]
Updates to the routes.

NB
- PR for this should be to `feature/update-routes` branch.

**Comment by tenorz007** [comment]
We don't need this, the reason we had that on the repository was because we were restructuring the repository... Just create feature branches and create PR into develop @SkaeX thoughts @BrainMaestro

**Comment by BrainMaestro** [comment]
We might need to have a conversation about the routes.

**Comment by BrainMaestro** [comment]
@SkaeX @tenorz007 did you notice that most of the routes are pointing to `SectionController` methods?
Not sure how that slipped under the radar.

**Comment by SkaeX** [comment]
Wow!

**Comment by BrainMaestro** [comment]
What should the route for updating evaluations look like?
