### ISSUE TITLE
Semester repository getQuestionSets

### ISSUE THREAD

**Issue by tenorz007** [BrainMaestro/FCE#67]
It doesn't need all that complication, it can be done using a transformer for ones that include pivot... @SkaeX @BrainMaestro

**Comment by BrainMaestro** [comment]
Actually that's not complicated. It's straightforward. Just excludes some keys that are not necessary. You're free to create a better solution.

**Comment by tenorz007** [comment]
What are you talking about? @BrainMaestro

**Comment by tenorz007** [comment]
I did........
