### ISSUE TITLE
Increment Evaluations

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#68]
Currently we increment evaluations one at a time. Which means if the user submitted an evaluation with 10 questions, we'll have to do 10 different queries. This can be improved. Thoughts? @tenorz007 @SkaeX

**Comment by SkaeX** [comment]
We had a similar conversation about creating `Question` in #38.

**Comment by BrainMaestro** [comment]
Well the difference is a bit subtle. For that one, we needed the returned value to build a relationship between `QuestionSet` and `Question`, and that was an operation that occurred rarely. 

This one is an operation that occurs frequently, and we don't need the return values.

Imagine that a section has 20 students each answering 20 questions. That'll be `20x20 (400)` database inserts. If we need to do for just 50 similar sections: `50x20x20 (20,000)` operations. I'm sure we can agree that this is huge

**Comment by SkaeX** [comment]
I know that. My point is, if we address this then we'll have to revisit #38.

**Comment by BrainMaestro** [comment]
No they're different. We can't bulk insert those one because we need the ids for the relationship. I mentioned that.

**Comment by tenorz007** [comment]
I fell we don't have to process them at once, we can process them all at the time the class is locked finally so we just do one operation by section

**Comment by SkaeX** [comment]
@tenorz007 please elaborate a little more.

**Comment by BrainMaestro** [comment]
That doesn't sound realistic. How can you get away with doing only one operation.


Sent from Outlook Mobile






On Sat, Mar 5, 2016 at 1:37 AM -0800, "tenorz007" <notifications@github.com> wrote:





I fell we don't have to process them at once, we can process them all at the time the class is locked finally so we just do one operation by section

---

**Comment by BrainMaestro** [comment]
This might not actually be possible. I'm closing this out until we figure it out

**Comment by SkaeX** [comment]
Why not? @BrainMaestro

**Comment by BrainMaestro** [comment]
That one has one where clause `->where('rowID', 1)` for all the rows to be updated, but we'll need one for each evaluation row.

**Comment by SkaeX** [comment]
I'll close this for now.
