### ISSUE TITLE
Unlocking and locking sections with helpers

### ISSUE THREAD

**Issue by BrainMaestro** [BrainMaestro/FCE#77]
In `v1`, helpers are created when a section is opened. This was because sections were opened from a central location by the `Admin` or `Secretary`. Though this worked well, it was tedious. Led to leaving a lot of classes unlocked. So we need a better solution.

**Comment by SkaeX** [comment]
We could do this:
- `Admin` unlocks a `QuestionSet` which creates `User`s with `helper` roles.
- `User`s with `helper` roles then unlock/lock `Section`s.

**Comment by BrainMaestro** [comment]
We might not even need to make them actual users. But yeah decent idea. @tenorz007 what do you think.

**Comment by BrainMaestro** [comment]
Hey @SkaeX. Sorry to say this, but we might need helpers to be users. To tie them into the authentication and authorization we're building. There doesn't seem to be any other way that's elegant enough. This would change almost everything you've done. 

cc @tenorz007

**Comment by SkaeX** [comment]
:sob:

**Comment by BrainMaestro** [comment]
If we're storing helpers as users, how do we keep the relationship between them and the sections? If we use the relationship between `User` and `Section`, that would involve inserting the helpers first, retrieving them and then using their `id` to create the relationship. That sounds like a bad idea to me. Thoughts?

**Comment by BrainMaestro** [comment]
Oh, and for each helper, I'm planning to represent them like this:
```
[
     'name' => $section['course_code'] . ' helper',
     'email' => '', // Not sure what the email field should contain.
     'password' => bcrypt($passkey),
]
```
How's that?

**Comment by SkaeX** [comment]
Hmm. @BrainMaestro please elaborate what is so bad about using the relationship.

**Comment by BrainMaestro** [comment]
We can't insert the helper user and the relationship at the same time. So we'll need to insert the users first. The retrieve them before inserting the relationship. That's the issue.





On Sun, Apr 10, 2016 at 12:26 PM -0700, "SkaeX" <notifications@github.com> wrote:





Hmm. @BrainMaestro please elaborate what is so bad about using the relationship.

---

**Comment by SkaeX** [comment]
I know that @BrainMaestro. I was wondering why that is so horrible.

**Comment by BrainMaestro** [comment]
A little inefficient? But not the end of the world. Guess it's fine. Just needed someone else's opinion.


Now that the helpers are users, we should probably just let them log in like regular users right? We can use the generated key as a password. But I'm not sure what the email field should contain.





On Sun, Apr 10, 2016 at 1:04 PM -0700, "SkaeX" <notifications@github.com> wrote:





I know that @BrainMaestro. I was wondering why that is so horrible.


---

**Comment by SkaeX** [comment]
How about `helper.<crn>@aun.edu.ng`

**Comment by SkaeX** [comment]
And remember 

> Premature optimization is the root of all evil - Donald Knuth

**Comment by BrainMaestro** [comment]
I like that. But can we trust then about the crn again?


And lol Knuth. Yeah I needed that.





On Sun, Apr 10, 2016 at 1:29 PM -0700, "SkaeX" <notifications@github.com> wrote:





How about `helper.<crn>@aun.edu.ng`

---

**Comment by SkaeX** [comment]
We could do `helper.<section_id>@aun.edu.ng`.

**Comment by BrainMaestro** [comment]
:+1:





On Sun, Apr 10, 2016 at 3:06 PM -0700, "SkaeX" <notifications@github.com> wrote:





We could do `helper.<section_id>@aun.edu.ng`.

---
