### ISSUE TITLE
Add necessary files for Keys

### ISSUE THREAD

**Issue by tenorz007** [BrainMaestro/FCE#9]

**Comment by BrainMaestro** [comment]
What?

**Comment by tenorz007** [comment]
Key is going to be a resource, and you were meant to add the necessary files, migrations, repository, transformer, model e.t.c.

**Comment by BrainMaestro** [comment]
I was meant to? We were meant to. Why can't you do it?

**Comment by tenorz007** [comment]
It's not about can or cannot do. You have a task you do it. I am still
going to work or most of the system while you are done. So I want you to do
your thing while you are around.

**Comment by BrainMaestro** [comment]
You should close the issues after you merge
